test_0_send (ETP.test_etp.TestSendETP) ... FAIL
test_1_sendfrom (ETP.test_etp.TestSendETP) ... FAIL
test_2_sendmore (ETP.test_etp.TestSendETP) ... FAIL
test_0_send (ETP.test_etp_boundary.TestSendETP) ... ok
test_1_sendfrom (ETP.test_etp_boundary.TestSendETP) ... ok
test_2_sendmore (ETP.test_etp_boundary.TestSendETP) ... ok

======================================================================
FAIL: test_0_send (ETP.test_etp.TestSendETP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/TestCase/ETP/test_etp.py", line 13, in test_0_send
    self.assertEqual(ec, 0, message)
AssertionError: no enough etp or asset in from address, or you are't own from address!

======================================================================
FAIL: test_1_sendfrom (ETP.test_etp.TestSendETP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/TestCase/ETP/test_etp.py", line 64, in test_1_sendfrom
    self.assertEqual(ec, 0, message)
AssertionError: no enough balance, unspent = 0, payment = 135642

======================================================================
FAIL: test_2_sendmore (ETP.test_etp.TestSendETP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/TestCase/ETP/test_etp.py", line 118, in test_2_sendmore
    self.assertEqual(ec, 0, message)
AssertionError: no enough etp or asset in from address, or you are't own from address!

----------------------------------------------------------------------
Ran 6 tests in 8.397s

FAILED (failures=3)
