test_0_multisig_2p3 (MultiSignature.test_multisig.TestMultiSig) ... FAIL
test_1_multisig_3p3 (MultiSignature.test_multisig.TestMultiSig) ... FAIL
test_0_getnew (MultiSignature.test_multisig_boundary.TestMultiSig)
test getnew(_multisig ... ok
test_1_list (MultiSignature.test_multisig_boundary.TestMultiSig)
test list_multisig ... ok
test_2_delete (MultiSignature.test_multisig_boundary.TestMultiSig)
test delete multisig addr ... FAIL

======================================================================
FAIL: test_0_multisig_2p3 (MultiSignature.test_multisig.TestMultiSig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/TestCase/MultiSignature/test_multisig.py", line 19, in test_0_multisig_2p3
    Alice.send_etp(addr_z, amount)
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/Roles.py", line 120, in send_etp
    assert (result == 0)
AssertionError

======================================================================
FAIL: test_1_multisig_3p3 (MultiSignature.test_multisig.TestMultiSig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/TestCase/MultiSignature/test_multisig.py", line 61, in test_1_multisig_3p3
    Alice.send_etp(addr_z, amount)
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/Roles.py", line 120, in send_etp
    assert (result == 0)
AssertionError

======================================================================
FAIL: test_2_delete (MultiSignature.test_multisig_boundary.TestMultiSig)
test delete multisig addr
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kesalin/projects/metaverse_nova/test/test-rpc/TestCase/MultiSignature/test_multisig_boundary.py", line 63, in test_2_delete
    self.assertEqual(ec, 5203, message)
AssertionError: invalid address! x

----------------------------------------------------------------------
Ran 5 tests in 5.819s

FAILED (failures=3)
